vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set number")
vim.cmd("set relativenumber")
vim.cmd("set ignorecase smartcase")
vim.cmd("set hlsearch")
vim.cmd("set incsearch")
vim.cmd("set guicursor=a:blinkon1")
vim.cmd("set guicursor=n:block,i:block-blinkwait100-blinkon100-blinkoff100")
vim.cmd([[highlight Normal guibg=NONE ctermbg=NONE]])
vim.cmd([[highlight NormalNC guibg=NONE ctermbg=NONE]])
vim.cmd([[highlight SignColumn guibg=NONE ctermbg=NONE]])
vim.cmd([[highlight VertSplit guibg=NONE ctermbg=NONE]])
vim.g.mapleader = " "
vim.keymap.set("n", "<leader>pv", ":Ex<CR>", {})
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv", {})
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv", {})
vim.keymap.set("n", "<C-d>", "<C-d>zz", {})
vim.keymap.set("n", "<C-u>", "<C-u>zz", {})
vim.keymap.set("n", "n", "nzzzv", {})
vim.keymap.set("n", "N", "Nzzzv", {})
vim.keymap.set("i", "<C-c>", "<Esc>", {})

